version: '3'

services:
  jarmalavicius.lt-web:
    container_name: jarmalavicius.lt-web
    build: .
    environment:
      VIRTUAL_HOST: www.jarmalavicius.lt,jarmalavicius.lt
      VIRTUAL_NETWORK: nginx_proxy
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.jarmalavicius.lt,jarmalavicius.lt
      LETSENCRYPT_EMAIL: remigijus@jarmalavicius.lt
    restart: always

networks:
  default:
    external:
      name: nginx_proxy
