version: '3'

services:
  jarmalavicius.lt-web:
    container_name: www.jarmalavicius.lt-web
    build: .
    environment:
      VIRTUAL_HOST: www.jarmalavicius.lt,jarmalavicius.lt
      VIRTUAL_NETWORK: nginx_proxy
      VIRTUAL_PORT: 80
    restart: always
    volumes:
      - /gems-cache

networks:
  default:
    external:
      name: nginx_proxy
