version: '3'

services:
  jarmalavicius.lt-web:
    container_name: jarmalavicius.lt-web
    image: jekyll/jekyll
    command: jekyll browsersync -- --no-notify
    ports:
      - 4000:4000
    volumes:
      - ./src:/srv/jekyll
