# Welcome to Jekyll!

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
email: remigijus@

include: ['_pages']
exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - purgecss.config.js
  - yarn.lock
  - node_modules
  - Gemfile
  - Gemfile.lock
  - webpack.config.js
  - _i18n
  - js

feed:
  path: rss.xml

responsive_image:
  template: _includes/srcset.html
  sizes:
   - width: 480
     quality: 90
   - width: 800
     quality: 90

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

permalink: /:categories/:title:output_ext

lang: 'lt'

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 100
  sort_reverse: true
