source 'https://rubygems.org'

# Platform
gem 'jekyll', '~> 4.0'

# Plugins
group :jekyll_plugins do
  gem 'jekyll-admin'
  gem 'jekyll-browsersync'
  gem 'jekyll-feed'
  gem 'jekyll-postcss'
  gem 'jekyll-purgecss'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-responsive-image'
  gem 'mini_racer'
  gem 'jekyll-minifier'
  gem 'jekyll-email-protect'
end
