# frozen_string_literal: true

source 'https://rubygems.org'

# Platform
gem 'jekyll', '~> 4.0'

# Plugins
group :jekyll_plugins do
  gem 'jekyll-browsersync'
  gem 'jekyll-compose'
  gem 'jekyll-email-protect'
  gem 'jekyll-minifier'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-postcss'
  gem 'jekyll-purgecss'
  gem 'jekyll-responsive-image'
  gem 'jekyll-sitemap'
  gem 'jekyll-toc'
end
