name: Production Deployment

on:
  push:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Directory Structure
      uses: ReekenX/github-ssh-action@master
      with:
        commands: |
          mkdir -p ~/projects/www.jarmalavicius.lt
          cd ~/projects/www.jarmalavicius.lt
          git init
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY}}

    - name: Upload recent changes to the server
      uses: ReekenX/github-ssh-action@master
      with:
        commands: |
          cd ~/projects/www.jarmalavicius.lt
          git pull -f https://github.com/ReekenX/www.jarmalavicius.lt
          git checkout -f master
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY}}

  build:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: Build project on the server
      uses: ReekenX/github-ssh-action@master
      with:
        commands: |
          cd ~/projects/www.jarmalavicius.lt
          docker-compose -f docker-compose.production.yml build
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY}}

  launch:
    runs-on: ubuntu-latest
    needs: [upload, build]
    steps:
    - name: Start fresh copy of the project
      uses: ReekenX/github-ssh-action@master
      with:
        commands: |
          cd ~/projects/www.jarmalavicius.lt
          docker-compose -f docker-compose.production.yml restart
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY}}
